spring.application.name=diningreview
spring.datasource.url = jdbc:h2:file:~/diningreview
spring.jackson.default-property-inclusion = NON_NULL
spring.jpa.defer-datasource-initialization = true
spring.jpa.hibernate.ddl-auto = create
